### ISSUE TITLE
Can this be used to add vst support to custom android audio engine that uses oboe ?

### ISSUE THREAD

**Issue by renetik** [RinoReyns/CrossPlatformVstHost#44]
I am not sure what you did here so asking simple quastion, how this repo can be usefull for android devs. Thanks.

Oboe is now stabdard for audio in android but not sure if this can be plugged into audio callback so I can use some vst plugins sources from github to get some nice reverb or so ? :)   Just asking I am not too much into cpp side but I developed some engine and wnat to have better audio fx there..

**Comment by RinoReyns** [comment]
Hi. Thanks for stopping by and leaving the question :) Let's say that this is my after hours project - just for fun and for exploration of VST writing and utilization. What I did here for android is a very basic .dll based on VST SDK which can load any VST Plugin and process audio data - currently in the "batching mode". By "batching mode" I mean that it takes long data buffer e.g. 30 seconds and process them. Currently there is no implementation for "streaming mode", so for processing single frame and returning it. So with some work it is possible to use it in your use case. Moreover, on the android side I mostly focused on integrating my .dll in Android environment, compiling my .dll as well as sample gain plugin from VST SDK and running it in the Instrumentation Test in CI on Github- which was quite challenging. I have never tested VST utilization in real-time android audio stack. I would be more then happy to work together on exploring the subject. 

In principle, yes if you would have source code of FX such as reverb you could compile it for android like I do this with Gain Plugin from VST SDK and use. 

Are you working on some after hours project? Or you planning to prepare some kind of product?

**Comment by renetik** [comment]
Yah what I work on is after hours project, if i  understand.. I already have releases multiple apps and plan more on android but was not able to make it profitable yet. Renetik Instruments, Renetik Mix, Renetik Fxrack... 
I am plannign to make Audio Looper, similar to loopy, Audio mastering app .. etc an improve what I have.. Add audio support to Instruments app so it is full futured DAW what it almost is....

But in terms of cooperation.. Lets say let me think about it... as I dont wqnt to distract myself from goals best would be if I can hire you in near future and pay from revenue from apps.. To make app appealing to professionals I need for sure better effects in the future.. For now I just steal c++ code of whatever effects on github and incorporate it if it go relatively easy...

I am just pushing update to all apps to fix some issues and performance.. so dotn try them yet ;)

**Comment by RinoReyns** [comment]
I'm sorry, but I'm not interested in being hired for such task and being paid. As I mentioned before this is my after hours project - I work on that in my free time, when I have time, mood and energy for that. Payment means obligations and more focus on project. This is not what this project is about. It is about learning. I do have regular job ;)
