### ISSUE TITLE
build AudioHostLib fail on macos 

### ISSUE THREAD

**Issue by alvminvm** [RinoReyns/CrossPlatformVstHost#45]
ANDROID_NDK_PATH=~/Library/Android/sdk/ndk/24.0.8215888

```
[CrossPlatformVstHost/VstHost_Android/build_arm64-v8a] $ANDROID_NDK_ROOT/prebuilt/darwin-x86_64/bin/make AudioHostLib                    
[  2%] Built target Logger
[  7%] Built target Common
[ 16%] Built target WaveIO
[ 23%] Built target pluginterfaces
[ 41%] Built target base
[ 55%] Built target sdk_common
[ 79%] Built target sdk
[ 94%] Built target sdk_hosting
[ 95%] Building CXX object modules/VstHost/CMakeFiles/AudioHostLib.dir/__/__/vst3sdk/public.sdk/source/vst/hosting/module_mac.mm.o
warning: unknown warning option '-Wsuggest-override'; did you mean '-Wshift-overflow'? [-Wunknown-warning-option]
error: -fobjc-arc is not supported on platforms using the legacy runtime
make[3]: *** [modules/VstHost/CMakeFiles/AudioHostLib.dir/build.make:104: modules/VstHost/CMakeFiles/AudioHostLib.dir/__/__/vst3sdk/public.sdk/source/vst/hosting/module_mac.mm.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:690: modules/VstHost/CMakeFiles/AudioHostLib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:697: modules/VstHost/CMakeFiles/AudioHostLib.dir/rule] Error 2
make: *** [Makefile:267: AudioHostLib] Error 2
```

**Comment by RinoReyns** [comment]
Hi @alvminvm. 

thanks for reporting the issue. However there is something wrong with your set up. Moreover, it looks like an issue from VST SDK. As a first step you can try to checkout the latest commit from VST SDK.

 For this repo I have CI. I just did dummy PR to check if it still works and indeed Mac OS build works fine. Here you can see the build log. https://github.com/RinoReyns/CrossPlatformVstHost/actions/runs/6864760168/job/18667250635

Can you give some more details on your set up e.g. what is the OS Version? Is it based on Intel processor or Apple ARM? Version of your compiler? CMake? XCode version?

I don't have MacOS set up on my site to somehow reproduce your env but maybe we can figure something out by analyzing your set up and the one which is executed in CI.

**Comment by RinoReyns** [comment]
I'm closing the issue due to no response.
